countries = ['siria', 'livia', 'iran', 'usa','cnr']
print(countries)
#Вывод без изменения списка
print(sorted(countries))
print(countries)
print(sorted(countries, reverse=True))
print(countries)
countries.reverse()
print(countries)
countries.reverse()
print(countries)
countries.sort()
print(countries)
countries.sort(reverse=True)
print(countries)
